@keycloak=http://localhost:8080/realms/cmsn/protocol/openid-connect
@client_secret=

### get token
POST {{keycloak}}/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&
client_id=cmsn&
client_secret={{client_secret}}&
username=&
password=&
scope=openid

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

###
@uri = http://localhost:9008/api/v1/departments

# Happy case
### Get the first page
GET {{uri}}
Authorization: Bearer {{access_token}}
Accept: application/json

# Happy case
### Get the first page
GET {{uri}}?keyword=02
Authorization: Bearer {{access_token}}
Accept: application/json

### U
### Happy case
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Name 1",
  "phoneNumber": "0949279204"
}

### Blank
POST {{uri}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "phoneNumber": ""
}

### duplicated name
POST {{uri}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Phòng Kế hoạch Kỹ Thuật",
  "phoneNumber": "0949279205"
}

### duplicated phone number
POST {{uri}}
Authorization: Bearer {{access_token}}
Accept: application/json
Content-Type: application/json

{
  "name": "shgdfh",
  "phoneNumber": "02283636681"
}

### D
### duplicated phone number
DELETE {{uri}}/hkggkgf
Authorization: Bearer {{access_token}}
Accept: application/json

### duplicated phone number
DELETE {{uri}}/e9fd7aa6-f047-4034-9835-b6020db944ef
Authorization: Bearer {{access_token}}
Accept: application/json
