package com.capstone.notification.service.impl;

import com.capstone.notification.dto.request.CreateNotificationRequest;
import com.capstone.notification.dto.response.IndividualNotificationResponse;
import com.capstone.notification.model.Notification;
import com.capstone.notification.repository.NotificationRepository;
import com.capstone.notification.service.boundary.AuthService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.PageRequest;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class NotificationServiceImplTest {

  @Mock
  NotificationRepository notificationRepo;

  @Mock
  AuthService authService;

  @InjectMocks
  NotificationServiceImpl notificationService;

  @Test
  @DisplayName("Create notification successfully")
  void should_CreateNotification_When_ValidRequest() {
    // Given
    var request = new CreateNotificationRequest("Title", "Message", "/link");
    var notification = Notification.builder()
      .title(request.title())
      .message(request.message())
      .link(request.link())
      .status(false)
      .build();

    when(notificationRepo.save(any(Notification.class))).thenReturn(notification);

    // When
    var response = notificationService.createNotification(request);

    // Then
    assertThat(response).isNotNull();
    assertThat(response.title()).isEqualTo(request.title());
    assertThat(response.message()).isEqualTo(request.message());
    assertThat(response.link()).isEqualTo(request.link());
    verify(notificationRepo, times(1)).save(any(Notification.class));
  }

  @Test
  @DisplayName("Get notifications successfully when user has notifications")
  void should_ReturnBatchResponse_When_UserHasNotifications() {
    // Given
    var userId = "user123";
    var pageable = PageRequest.of(0, 10);
    var notificationId = "notif1";

    var individualResponse = new IndividualNotificationResponse(notificationId, false);
    List<IndividualNotificationResponse> individualList = List.of(individualResponse);

    var notificationEntity = Notification.builder()
      .title("Title")
      .message("Message")
      .link("/link")
      .status(false)
      .build();
    // Set notificationId manually as it's normally generated by DB
    // Since it's final-like field in record or using setter? Notification uses
    // private fields.
    // I can mock the getId if I use a mock, but here it's an entity.
    // Let's use reflection to set ID if required, or trust the builder if I could.
    // Actually the convert method uses value.getNotificationId().

    when(authService.getIndividualNotificationsOfAnEmployee(pageable, userId)).thenReturn(individualList);
    when(notificationRepo.findById(notificationId)).thenReturn(Optional.of(notificationEntity));

    // When
    var response = notificationService.getNotificationsOfAnEmployee(pageable, userId);

    // Then
    assertThat(response).isNotNull();
    assertThat(response.items()).hasSize(1);
    assertThat(response.items().getFirst().title()).isEqualTo(notificationEntity.getTitle());
    assertThat(response.totalFound()).isEqualTo(1);
    verify(authService, times(1)).getIndividualNotificationsOfAnEmployee(pageable, userId);
    verify(notificationRepo, times(1)).findById(notificationId);
  }

  @Test
  @DisplayName("Get notifications returns null when user has no notifications from auth service")
  void should_ReturnNull_When_UserHasNoNotifications() {
    // Given
    var userId = "userEmpty";
    var pageable = PageRequest.of(0, 10);

    when(authService.getIndividualNotificationsOfAnEmployee(pageable, userId)).thenReturn(Collections.emptyList());

    // When
    var response = notificationService.getNotificationsOfAnEmployee(pageable, userId);

    // Then
    assertThat(response).isNull();
    verify(authService, times(1)).getIndividualNotificationsOfAnEmployee(pageable, userId);
    verifyNoInteractions(notificationRepo);
  }

  @Test
  @DisplayName("Get notifications should skip if notification entity not found in repository")
  void should_SkipNotification_When_EntityNotFoundInRepo() {
    // Given
    var userId = "userMissing";
    var pageable = PageRequest.of(0, 10);
    var notificationId = "missingNotif";

    var individualResponse = new IndividualNotificationResponse(notificationId, false);
    List<IndividualNotificationResponse> individualList = List.of(individualResponse);

    when(authService.getIndividualNotificationsOfAnEmployee(pageable, userId)).thenReturn(individualList);
    when(notificationRepo.findById(notificationId)).thenReturn(Optional.empty());

    // When
    var response = notificationService.getNotificationsOfAnEmployee(pageable, userId);

    // Then
    assertThat(response).isNotNull();
    assertThat(response.items()).isEmpty();
    assertThat(response.totalFound()).isEqualTo(1);
    verify(notificationRepo, times(1)).findById(notificationId);
  }

  @Test
  @DisplayName("Get notifications should sort by createdAt descending")
  void should_SortNotificationsByCreatedAtDescending() {
    // Given
    var userId = "userSort";
    var pageable = PageRequest.of(0, 10);

    var n1 = Notification.builder().title("Old").build();
    ReflectionTestUtils.setField(n1, "notificationId", "id1");
    ReflectionTestUtils.setField(n1, "createdAt", java.time.LocalDateTime.now().minusDays(1));

    var n2 = Notification.builder().title("New").build();
    ReflectionTestUtils.setField(n2, "notificationId", "id2");
    ReflectionTestUtils.setField(n2, "createdAt", java.time.LocalDateTime.now());

    var indList = List.of(
      new IndividualNotificationResponse("id1", false),
      new IndividualNotificationResponse("id2", false)
    );

    when(authService.getIndividualNotificationsOfAnEmployee(pageable, userId)).thenReturn(indList);
    when(notificationRepo.findById("id1")).thenReturn(Optional.of(n1));
    when(notificationRepo.findById("id2")).thenReturn(Optional.of(n2));

    // When
    var response = notificationService.getNotificationsOfAnEmployee(pageable, userId);

    // Then
    assertThat(response.items()).hasSize(2);
    assertThat(response.items().get(0).title()).isEqualTo("New");
    assertThat(response.items().get(1).title()).isEqualTo("Old");
  }

  @Test
  @DisplayName("Get unread count successfully")
  void should_GetUnreadCount() {
    when(authService.getUnreadCount("u1")).thenReturn(5L);
    assertThat(notificationService.getUnreadCount("u1")).isEqualTo(5L);
  }

  @Test
  @DisplayName("Mark as read successfully")
  void should_MarkAsRead() {
    notificationService.markAsRead("u1", "n1");
    verify(authService).markAsRead("u1", "n1");
  }

  @Test
  @DisplayName("Delete notification successfully")
  void should_DeleteNotification() {
    notificationService.deleteNotification("u1", "n1");
    verify(authService).deleteNotification("u1", "n1");
  }
}
