@uri = http://localhost:9004/api/v1/laterals
@keycloak=http://localhost:8080/realms/cmsn/protocol/openid-connect
@client_secret=

### get token
POST {{keycloak}}/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=password&
client_id=&
client_secret={{client_secret}}&
username=&
password=&
scope=openid

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### C
### happy case
POST {{uri}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "ueueue",
  "networkId": "550e8400-e29b-41d4-a716-446655440001"
}

### blank name
POST {{uri}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "",
  "networkId": ""
}

### blank networkId
POST {{uri}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "uuss",
  "networkId": ""
}

### network does not exist
POST {{uri}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "adadf",
  "networkId": "550e8400-e29b-41d4-a716-446655440000"
}

### duplicated name
POST {{uri}}
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "ueueue",
  "networkId": "550e8400-e29b-41d4-a716-446655440001"
}

### R

### R - get all laterals (no filter)
GET {{uri}}?page=0&size=10
Authorization: Bearer {{access_token}}
Accept: application/json

### R - search laterals by keyword (name or network name)
GET {{uri}}?page=0&size=10&keyword=A300
Authorization: Bearer {{access_token}}
Accept: application/json

### R - filter laterals by networkId
GET {{uri}}?page=0&size=10&networkId=550e8400-e29b-41d4-a716-446655440001
Authorization: Bearer {{access_token}}
Accept: application/json

### R - filter laterals with assigned network only
GET {{uri}}?page=0&size=10&networkAssigned=true
Authorization: Bearer {{access_token}}
Accept: application/json

### R - filter laterals with no network assigned
GET {{uri}}?page=0&size=10&networkAssigned=false
Authorization: Bearer {{access_token}}
Accept: application/json

### R - combine keyword + networkId + assigned filter
GET {{uri}}?page=0&size=10&keyword=A300&networkId=550e8400-e29b-41d4-a716-446655440001&networkAssigned=true
Authorization: Bearer {{access_token}}
Accept: application/json

### U
### happy case
PUT {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "ueueue2",
  "networkId": "550e8400-e29b-41d4-a716-446655440001"
}

### blank name
PUT {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "",
  "networkId": ""
}

### blank networkId
PUT {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "uuss",
  "networkId": ""
}

### network does not exist
PUT {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "adadf",
  "networkId": "550e8400-e29b-41d4-a716-446655440000"
}

### duplicated name
PUT {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

{
  "name": "ueueue",
  "networkId": "550e8400-e29b-41d4-a716-446655440002"
}

### D
### happy case
DELETE {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac192
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json

### id not found
DELETE {{uri}}/a36278db-45a3-44a8-86cf-6be81bfac193
Content-Type: application/json
Authorization: Bearer {{access_token}}
Accept: application/json
