

### TC01 - Tạo mới biên lai thành công (Happy Path)
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "formCode": "b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a12",
  "formNumber": "FORM-2024-0002",
  "receiptNumber": "BL-99999",
  "customerName": "Nguyễn Văn A",
  "address": "123 Đường ABC, Quận 1, TP.HCM",
  "paymentDate": "2024-03-19",
  "isPaid": true
}

> {%
client.test("Status is 201", function() {
  client.assert(response.status === 201);
});
%}


### TC02 - Thiếu trường mã đơn (formNumber)
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "receiptNumber": "BL-99999",
  "customerName": "A",
  "address": "Addr",
  "paymentDate": "2024-03-19",
  "isPaid": true
}

> {%
client.test("Status is 400", function() {
  client.assert(response.status === 400);
});
%}


### TC03 - Số biên lai rỗng (Empty String)
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "formNumber": "20240319001",
  "receiptNumber": "",
  "customerName": "A",
  "address": "Addr",
  "paymentDate": "2024-03-19",
  "isPaid": true
}

> {%
client.test("Status is 400", function() {
  client.assert(response.status === 400);
});
%}


### TC04 - Ngày thanh toán sai định dạng
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "formNumber": "20240319001",
  "receiptNumber": "BL-001",
  "paymentDate": "19/03/2024"
}

> {%
client.test("Status is 400", function() {
  client.assert(response.status === 400);
});
%}


### TC05 - Cập nhật biên lai thành công
PUT http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "formNumber": "20240319001",
  "receiptNumber": "BL-UPDATED",
  "isPaid": false
}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC06 - Lấy chi tiết biên lai thành công
GET http://localhost:9004/api/v1/receipts/LD/20240319001
Authorization: Bearer {{auth_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC07 - Xoá biên lai thành công
DELETE http://localhost:9004/api/v1/receipts/LD/20240319001
Authorization: Bearer {{auth_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC08 - Truy cập không có quyền (Security)
GET http://localhost:9004/api/v1/receipts/LD/20240319001

> {%
client.test("Status is 401", function() {
  client.assert(response.status === 401);
});
%}


### TC09 - Lỗi nghiệp vụ: Đơn chưa có dự toán được duyệt
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "formNumber": "FORM_UNAUTHORIZED_ESTIMATE",
  "receiptNumber": "BL-001",
  "customerName": "A",
  "address": "Addr",
  "paymentDate": "2024-03-19",
  "isPaid": true
}

> {%
client.test("Status is 400", function() {
  client.assert(response.status === 400);
});
%}


### TC10 - Malformed JSON
POST http://localhost:9004/api/v1/receipts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "formCode": "LD",
  "formNumber": "2024001",
  "receiptNumber": "BL001"
  "isPaid": true
}

> {%
client.test("Status is 400", function() {
  client.assert(response.status === 400);
});
%}


### TC11 - Lấy danh sách biên lai với phân trang
GET http://localhost:9004/api/v1/receipts?page=0&size=10
Authorization: Bearer {{access_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC12 - Lọc danh sách biên lai theo từ khóa
GET http://localhost:9004/api/v1/receipts?keyword=Nguyễn&page=0&size=10
Authorization: Bearer {{access_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC13 - Lọc danh sách biên lai theo khoảng thời gian
GET http://localhost:9004/api/v1/receipts?from=01-01-2024&to=31-12-2024&page=0&size=10
Authorization: Bearer {{access_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC14 - Lọc danh sách biên lai theo trạng thái thanh toán
GET http://localhost:9004/api/v1/receipts?isPaid=true&page=0&size=10
Authorization: Bearer {{access_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC15 - Lọc kết hợp nhiều điều kiện
GET http://localhost:9004/api/v1/receipts?keyword=A&from=01-01-2024&to=31-12-2024&isPaid=true&page=0&size=10
Authorization: Bearer {{access_token}}

> {%
client.test("Status is 200", function() {
  client.assert(response.status === 200);
});
%}


### TC15 - Lọc kết hợp nhiều điều kiện
GET http://localhost:9004/api/v1/receipts/last
Authorization: Bearer {{access_token}}

> {%
  client.test("Status is 200", function() {
    client.assert(response.status === 200);
  });
%}
