@keycloak = http://localhost:8080/realms/cmsn/protocol/openid-connect
@client_secret =

### get token
POST {{keycloak}}/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type = password &
client_id =  &
client_secret = {{client_secret}} &
username =  &
password =  &
scope = openid

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### main endpoint
@uri = http://localhost:9003/api/v1/me

### me
GET {{uri}}
Authorization: Bearer {{access_token}}
Accept: application/json

### Update profile, some fields are nullable
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "hoan",
  "username": null,
  "phoneNumber": null,
  "birthdate": null,
  "address": null,
  "gender": null
}

### Update profile, all fields are not nullable 0
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "Trần Xuân Hoàn",
  "username": "test",
  "phoneNumber": "1234567890",
  "birthdate": "2013-10-10",
  "address": "address",
  "gender": true
}

### Update profile, all fields are not nullable 1; fullname contains digits or special characters
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "fullname1",
  "username": "test",
  "phoneNumber": "1234567890",
  "birthdate": "2013-10-10",
  "address": "address",
  "gender": true
}

### Update profile, all fields are not nullable 2; phone number is only 9 digits
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "hoan",
  "username": "admin1",
  "phoneNumber": "123456789",
  "birthdate": "2013-10-10",
  "address": "address",
  "gender": false
}

### Update profile, all fields are not nullable 3; problem in birthdate
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "hoan",
  "username": "admin1",
  "phoneNumber": "1234567890",
  "birthdate": "2013",
  "address": "address",
  "gender": false
}

### Update profile, all fields are blank
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "",
  "username": "",
  "phoneNumber": "",
  "birthdate": "",
  "address": "",
  "gender": false
}

### Update profile, except of birthdate and phoneNumber, all fields are blank
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json
Accept: application/json

{
  "fullName": "",
  "username": "",
  "phoneNumber": "0912345678",
  "birthdate": "2013-10-10",
  "address": "",
  "gender": false
}

### Update profile, fullname is Vietnamese
POST {{uri}}
Authorization: Bearer {{access_token}}
Content-Type: application/json; charset=UTF-8
Accept: application/json

{
  "fullName": "Trần Xuân Hoàn",
  "username": "admin1",
  "phoneNumber": "1234567890",
  "birthdate": "2013-10-10",
  "address": "address1",
  "gender": true
}

### Update avatar
PUT {{uri}}
Content-Type: multipart/form-data; boundary=boundary
Accept: application/json
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="avatar"; filename="img.png"
Content-Type: image/jpeg

< ./img.png
--boundary--
