package com.capstone.common.enumerate;

public enum RoleName {
  IT_STAFF,
  PLANNING_TECHNICAL_DEPARTMENT_HEAD,
  SURVEY_STAFF,
  ORDER_RECEIVING_STAFF,
  FINANCE_DEPARTMENT,
  CONSTRUCTION_DEPARTMENT_HEAD,
  CONSTRUCTION_DEPARTMENT_STAFF,
  BUSINESS_DEPARTMENT_HEAD,
  METER_INSPECTION_STAFF,
  COMPANY_LEADERSHIP
}
