spring:
  application:
    name: customer
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 5 # nang core khi co nhieu truy van song song
      minimum-idle: 3 # So ket noi idle luon co san
      connection-timeout: 2000 # Cho ket noi toi da 3s
      max-lifetime: 600000 # Ket noi song toi da 30p
      idle-timeout: 30000 # Dong idle sau 30s neu khong su dung
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
      base-path: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
server:
  port: 9005
  servlet:
    context-path: /api/v1
web-frontend-url: ${WEB_FRONTEND_URL:http://localhost:3000}
cors:
  allowed-origins:
    - ${web-frontend-url}
