services:
  eureka-service:
    image: ghcr.io/tranhoan-backend-dev/capstone-project/eureka:latest
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  api-gateway:
    depends_on:
      - eureka-service
    image: ghcr.io/tranhoan-backend-dev/capstone-project/gateway:latest
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  auth-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/auth:latest
    ports:
      - "9003:9003"
    environment:
      SERVER_PORT: 9003
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  construction-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/construction:latest
    ports:
      - "9004:9004"
    environment:
      SERVER_PORT: 9004
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  customer-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/customer:latest
    ports:
      - "9005:9005"
    environment:
      SERVER_PORT: 9005
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  device-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/device:latest
    ports:
      - "9006:9006"
    environment:
      SERVER_PORT: 9006
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  notification-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/notification:latest
    ports:
      - "9007:9007"
    environment:
      SERVER_PORT: 9007
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  organization-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/organization:latest
    ports:
      - "9008:9008"
    environment:
      SERVER_PORT: 9008
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  image-service:
    depends_on:
      - api-gateway
    image: ghcr.io/tranhoan-backend-dev/capstone-project/image:latest
    ports:
      - "9009:9009"
    environment:
      SERVER_PORT: 9009
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - app-network

  email-service:
    image: ghcr.io/tranhoan-backend-dev/capstone-project/email:latest
    ports:
      - "3000:9010"
    networks:
      - app-network

networks:
  app-network: